# ** Insper - Acionamentos Elétricos**

**Aula 02**

**Exercício 01**
No circuito abaixo, construa e resolva o sistema linear de equações para encontrar as correntes.



In [3]:
from IPython.display import Image
# Image(filename="circuito.png")

Equacionando os nós:
\begin{align*}
i_1 -i_4-i_5 &=0\\
i_5 -i_2 - i_7&=0\\
i_7 - i_3 -i_6 &= 0
\end{align*}
Equacionando as malhas:
\begin{align*}
5 - R_1 i_i -R_4 i_4 &= 0\\
R_4 i_4 - 2,17 - R_2 i_2 &= 0\\
R_2 i_2 - R_3 i_3 &= 0\\
R_3 i_3 - R_6 i_6 &= 0
\end{align*}
A equação na forma matricial fica:
\begin{align*}
\mathbf{A} \times \mathbf{I} = \mathbf{V}
\end{align*}

\begin{align*}
\begin{pmatrix}
1  &  0  &  0  &  -1  &  -1  &  0  &  0\\
    0  &  -1  &  0  &  0  &  1  &  0  &  -1\\
    0  &  0  &  -1  &  0  &  0  &  -1  &  1\\
    -R_1  &  0  &  0  &  -R_4  &  0  &  0  &  0\\
    0  &  -R_2  &  0  &  R_4  &  0  &  0  &  0\\
    0  &  R_2  &  -R_3  &  0  &  0  &  0  &  0\\
    0  &  0  &  R_3  &  0  &  0  &  -R_6  &  0
\end{pmatrix} 
\times
\begin{pmatrix}
i_1\\i_2\\i_3\\i_4\\i_5\\i_6\\i_7
\end{pmatrix}
&=
\begin{pmatrix}
0\\0\\0\\-5\\2,17\\0\\0
\end{pmatrix}
\end{align*}

E invertendo a matriz A podemos descobrir o vetor de correntes I:
\begin{align*}
\mathbf{I} = \mathbf{A}^{-1} \times \mathbf{V}
\end{align*}

In [4]:
# Implementação do exercício 2
# Constantes
Vled = 2.17
R1 = 47
R2 = 62
R3 = 100
R4 = 470
R6 = 220

# Matriz das "Resistências" A: Como criávamos uma matrix no Python?
A = [[1,-1,-1],[-5,0,0],[0,0,10]]

# Matriz (Vetor) das constantes de tensão dentro das malhas
V = [0,0,0,-5,2.17,0,0]

# Vamos imprimir as matrizes para verificar se está tudo certo.
# Visualização como matrizes (np.array). Obs: Formalmente o vetor V
#   é um vetor coluna, por isso utilizamos a transposta (.T).

import numpy as np
A = np.array(A)
V = np.array([V]).T
print("Matriz A: \n", A)
print("\nVetor  V: \n", V)

Matriz A: 
 [[ 1 -1 -1]
 [-5  0  0]
 [ 0  0 10]]

Vetor  V: 
 [[ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [-5.  ]
 [ 2.17]
 [ 0.  ]
 [ 0.  ]]


In [5]:
import numpy as np
from scipy import linalg
# dot product of A^-1 and V
I=np.dot(linalg.inv(A),V)

# Correntes em Amperes
print("Correntes:")
print("i1 = ", '%6.4f'% I[0], "A")
print("i2 = ", '%6.4f'% I[1], "A")
print("i3 = ", '%6.4f'% I[2], "A")
print("i4 = ", '%6.4f'% I[3], "A")
print("i5 = ", '%6.4f'% I[4], "A")
print("i6 = ", '%6.4f'% I[5], "A")
print("i7 = ", '%6.4f'% I[6], "A")

# As correntes são muito pequeninas, vamos exibir os valores em mA
print("\n\nCorrentes em mA:")
print("i1 = ", '%06.4f' % (1000*I[0]), "mA")
print("i2 = ", '%06.4f' % (1000*I[1]), "mA")
print("i3 = ", '%06.4f' % (1000*I[2]), "mA")
print("i4 = ", '%06.4f' % (1000*I[3]), "mA")
print("i5 = ", '%06.4f' % (1000*I[4]), "mA")
print("i6 = ", '%06.4f' % (1000*I[5]), "mA")
print("i7 = ", '%06.4f' % (1000*I[6]), "mA")


ValueError: shapes (3,3) and (7,1) not aligned: 3 (dim 1) != 7 (dim 0)